version: '2'
services:
  fpm:
    build: ./php
    volumes:
    - ./html:/var/www/html:delegated
  apache:
    image: webdevops/apache:alpine-3
    ports:
      - '80'
    environment:
      WEB_PHP_SOCKET: fpm:9000
      WEB_DOCUMENT_ROOT: /var/www/html
    volumes:
    - ./html:/var/www/html:delegated
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitrix
  adminer:
    image: adminer